name: base
channels:
  - sepandhaghighi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.3
  - ansiwrap=0.8.4
  - art=5.3
  - async_generator=1.10
  - attrs=21.2.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - black=21.9b0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - cryptography=3.4.7
  - curl=7.79.1
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=4.4.2
  - entrypoints=0.3
  - expat=2.4.1
  - fiona=1.8.20
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gdal=3.3.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - graphite2=1.3.13
  - gsl=2.7
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=2.9.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.1
  - importlib-metadata=4.8.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - joblib=1.0.1
  - jpeg=9d
  - jq=1.6
  - json-c=0.15
  - jsonschema=4.0.1
  - jupyter_client=7.0.5
  - jupyter_core=4.8.1
  - kealib=1.4.14
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.79.1
  - libdap4=3.20.6
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.2.0
  - libgdal=3.3.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgit2=1.3.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.17
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.18.0
  - librttopo=1.1.0
  - libsanitizer=9.4.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libv8=8.9.83
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - loguru=0.5.3
  - lz4-c=1.9.3
  - make=4.3
  - mapclassify=2.4.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - munch=2.5.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclient=0.5.4
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - nspr=4.30
  - nss=3.69
  - numpy=1.21.2
  - olefile=0.46
  - oniguruma=6.9.7.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pandas=1.3.3
  - pango=1.48.10
  - papermill=2.3.3
  - pathspec=0.9.0
  - pcre=8.45
  - pcre2=10.37
  - pillow=8.3.2
  - pip=21.2.4
  - pixman=0.40.0
  - platformdirs=2.3.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.0
  - pthread-stubs=0.4
  - pycm=3.2
  - pycparser=2.20
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyproj=3.2.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - qt=5.12.9
  - r-abind=1.4_5
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.2.1
  - r-base=4.1.1
  - r-base64enc=0.1_3
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-boot=1.3_28
  - r-brew=1.0_6
  - r-brio=1.1.2
  - r-broom=0.7.9
  - r-cachem=1.0.6
  - r-callr=3.7.0
  - r-car=3.0_11
  - r-cardata=3.0_4
  - r-cellranger=1.1.0
  - r-class=7.3_19
  - r-classint=0.4_3
  - r-cli=3.0.1
  - r-clipr=0.7.1
  - r-colorspace=2.0_2
  - r-commonmark=1.7
  - r-conquer=1.0.2
  - r-corrplot=0.90
  - r-covr=3.5.1
  - r-cowplot=1.1.1
  - r-cpp11=0.4.0
  - r-crayon=1.4.1
  - r-credentials=1.3.1
  - r-crosstalk=1.1.1
  - r-crul=1.1.0
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbi=1.1.1
  - r-desc=1.4.0
  - r-devtools=2.4.2
  - r-diffobj=0.3.4
  - r-digest=0.6.28
  - r-dplyr=1.0.7
  - r-dt=0.19
  - r-e1071=1.7_9
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=0.4.2
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-forcats=0.5.1
  - r-foreign=0.8_81
  - r-fs=1.5.0
  - r-generics=0.1.0
  - r-geojson=0.3.4
  - r-geojsonio=0.9.4
  - r-geojsonsf=2.0.1
  - r-geometries=0.2.0
  - r-gert=1.4.1
  - r-ggalluvial=0.12.3
  - r-ggfittext=0.9.1
  - r-ggplot2=3.3.5
  - r-ggpubr=0.4.0
  - r-ggrepel=0.9.1
  - r-ggsci=2.9
  - r-ggsignif=0.6.3
  - r-gh=1.3.0
  - r-git2r=0.28.0
  - r-gitcreds=0.1.1
  - r-glue=1.4.2
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-haven=2.4.3
  - r-highr=0.9
  - r-hms=1.1.1
  - r-htmltools=0.5.2
  - r-htmlwidgets=1.5.4
  - r-httpcode=0.3.0
  - r-httr=1.4.2
  - r-ini=0.3.1
  - r-irdisplay=1.0
  - r-irkernel=1.2
  - r-isoband=0.2.5
  - r-jqr=1.2.1
  - r-jquerylib=0.1.4
  - r-jsonify=1.2.1
  - r-jsonlite=1.7.2
  - r-kernsmooth=2.23_20
  - r-knitr=1.35
  - r-labeling=0.4.2
  - r-later=1.2.0
  - r-lattice=0.20_45
  - r-lazyeval=0.2.2
  - r-leaflet=2.0.4.1
  - r-leaflet.providers=1.9.0
  - r-lifecycle=1.0.1
  - r-lme4=1.1_27.1
  - r-magrittr=2.0.1
  - r-maptools=1.1_2
  - r-markdown=1.1
  - r-mass=7.3_54
  - r-matrix=1.3_4
  - r-matrixmodels=0.5_0
  - r-matrixstats=0.61.0
  - r-memoise=2.0.0
  - r-mgcv=1.8_37
  - r-mime=0.12
  - r-minqa=1.2.4
  - r-munsell=0.5.0
  - r-nlme=3.1_153
  - r-nloptr=1.2.2.2
  - r-nnet=7.3_16
  - r-numderiv=2016.8_1.1
  - r-openssl=1.4.5
  - r-openxlsx=4.2.4
  - r-pbdzmq=0.3_5
  - r-pbkrtest=0.5.1
  - r-pillar=1.6.3
  - r-pkgbuild=1.2.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.2
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-polynom=1.4_0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.5.2
  - r-progress=1.2.2
  - r-promises=1.2.0.1
  - r-protolite=2.1.1
  - r-proxy=0.4_26
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-quantreg=5.86
  - r-r6=2.5.1
  - r-rapidjsonr=1.2.0
  - r-rappdirs=0.3.3
  - r-raster=3.4_13
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.7
  - r-rcpparmadillo=0.10.7.0.0
  - r-rcppeigen=0.3.3.9.1
  - r-readr=2.0.2
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-remotes=2.4.1
  - r-repr=1.1.3
  - r-reshape2=1.4.4
  - r-rex=1.2.0
  - r-rgeos=0.5_8
  - r-rio=0.5.27
  - r-rlang=0.4.11
  - r-roxygen2=7.1.2
  - r-rprojroot=2.0.2
  - r-rstatix=0.7.0
  - r-rstudioapi=0.13
  - r-rversions=2.1.1
  - r-s2=1.0.7
  - r-scales=1.1.1
  - r-sessioninfo=1.1.1
  - r-sf=1.0_2
  - r-sfheaders=0.4.0
  - r-shades=1.4.0
  - r-sp=1.4_5
  - r-sparsem=1.81
  - r-statmod=1.4.36
  - r-stringi=1.7.4
  - r-stringr=1.4.0
  - r-sys=3.4
  - r-testthat=3.0.4
  - r-tibble=3.1.5
  - r-tidyr=1.1.4
  - r-tidyselect=1.1.1
  - r-triebeard=0.3.0
  - r-tzdb=0.1.2
  - r-units=0.7_2
  - r-urltools=1.7.3
  - r-usethis=2.0.1
  - r-utf8=1.2.2
  - r-uuid=0.1_4
  - r-v8=3.4.2
  - r-vctrs=0.3.8
  - r-viridis=0.6.1
  - r-viridislite=0.4.0
  - r-vroom=1.5.5
  - r-waldo=0.3.1
  - r-whisker=0.4
  - r-withr=2.4.2
  - r-wk=0.5.0
  - r-xfun=0.26
  - r-xml2=1.3.2
  - r-xopen=1.0.0
  - r-yaml=2.2.1
  - r-zip=2.2.0
  - readline=8.1
  - regex=2021.9.30
  - requests=2.26.0
  - rtree=0.9.7
  - scikit-learn=1.0
  - scipy=1.7.1
  - sed=4.8
  - setuptools=58.0.4
  - shapely=1.7.1
  - six=1.16.0
  - sqlite=3.36.0
  - sysroot_linux-64=2.12
  - tenacity=8.0.1
  - textwrap3=0.9.2
  - threadpoolctl=3.0.0
  - tiledb=2.3.4
  - tinydb=4.5.2
  - tk=8.6.11
  - tktable=2.10
  - tomli=1.2.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzcode=2021a
  - tzdata=2021a
  - udunits2=2.2.27.27
  - urllib3=1.26.7
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.1
  - zlib=1.2.11
  - zstd=1.5.0
  # Adapted from: https://github.com/jupyterhub/repo2docker/blob/HEAD/repo2docker/buildpacks/conda/environment.yml
  - ipywidgets==7.6.3
  - jupyter-offlinenotebook==0.2.1
  - jupyter-resource-usage==0.6.0
  - jupyterlab==3.1.11
  - jupyterhub-singleuser==1.4.2
  # Newer versions require python 3.7
  - nbconvert==6.0.7
  # 6.4.0 conda package requires python 3.7
  - notebook==6.3.0
  - nteract_on_jupyter==2.1.3
  - pip:
    - charset-normalizer==2.0.6
    - descartes==1.1.0
    - idna==3.2
    - jinja2==3.0.1
    - jsonschema==4.0.1
    - git+https://github.com/brazil-data-cube/lccs.py@v0.8.0
    - git+https://github.com/brazil-data-cube/wlts.py@v0.8.0
    - lxml==4.6.3
    - markupsafe==2.0.1
    - pyrsistent==0.18.0
    - python-sld==1.0.10
    - requests==2.26.0
    - urllib3==1.26.7
